const themes = [
  { label: "Opening", value: "opening", category: "phases" },
  { label: "Middlegame", value: "middlegame", category: "phases" },
  { label: "Endgame", value: "endgame", category: "phases" },
  { label: "Pawn endgame", value: "pawnEndgame", category: "phases" },
  { label: "Knight endgame", value: "knightEndgame", category: "phases" },
  { label: "Bishop endgame", value: "bishopEndgame", category: "phases" },
  { label: "Rook endgame", value: "rookEndgame", category: "phases" },
  { label: "Queen endgame", value: "queenEndgame", category: "phases" },
  { label: "Queen and Rook", value: "queenAndRook", category: "phases" },
  { label: "Advanced pawn", value: "advancedPawn", category: "motifs" },
  {
    label: "Attacking f2 or f7",
    value: "attackingF2OrF7",
    category: "motifs",
  },
  {
    label: "Capture the defender",
    value: "captureTheDefender",
    category: "motifs",
  },
  {
    label: "Discovered attack",
    value: "discoveredAttack",
    category: "motifs",
  },
  { label: "Double check", value: "doubleCheck", category: "motifs" },
  { label: "Exposed king", value: "exposedKing", category: "motifs" },
  { label: "Fork", value: "fork", category: "motifs" },
  { label: "Hanging piece", value: "hangingPiece", category: "motifs" },
  { label: "Kingside attack", value: "kingsideAttack", category: "motifs" },
  { label: "Pin", value: "pin", category: "motifs" },
  { label: "Queenside attack", value: "queensideAttack", category: "motifs" },
  { label: "Skewer", value: "skewer", category: "motifs" },
  { label: "Sacrifice", value: "sacrifice", category: "motifs" },
  { label: "Trapped piece", value: "trappedPiece", category: "motifs" },
  { label: "Attraction", value: "attraction", category: "advanced" },
  { label: "Clearance", value: "clearance", category: "advanced" },
  { label: "Defensive move", value: "defensiveMove", category: "advanced" },
  { label: "Deflection", value: "deflection", category: "advanced" },
  { label: "Interference", value: "interference", category: "advanced" },
  { label: "Intermezzo", value: "intermezzo", category: "advanced" },
  { label: "Quiet move", value: "quietMove", category: "advanced" },
  { label: "X-Ray attack", value: "xRayAttack", category: "advanced" },
  { label: "Zugzwang", value: "zugzwang", category: "advanced" },
  { label: "Checkmate", value: "checkmate", category: "mates" },
  { label: "Mate in 1", value: "mateIn1", category: "mates" },
  { label: "Mate in 2", value: "mateIn2", category: "mates" },
  { label: "Mate in 3", value: "mateIn3", category: "mates" },
  { label: "Mate in 4", value: "mateIn4", category: "mates" },
  { label: "Mate in 5 or more", value: "mateIn5", category: "mates" },
  { label: "Anastasia's mate", value: "anastasiaMate", category: "mates" },
  { label: "Arabian mate", value: "arabianMate", category: "mates" },
  { label: "Back rank mate", value: "backRankMate", category: "mates" },
  { label: "Boden's mate", value: "bodenMate", category: "mates" },
  {
    label: "Double bishop mate",
    value: "doubleBishopMate",
    category: "mates",
  },
  { label: "Dovetail mate", value: "dovetailMate", category: "mates" },
  { label: "Hook mate", value: "hookMate", category: "mates" },
  { label: "Smothered mate", value: "smotheredMate", category: "mates" },
  { label: "Castling", value: "castling", category: "specialMoves" },
  { label: "En passant", value: "enPassant", category: "specialMoves" },
  { label: "Promotion", value: "promotion", category: "specialMoves" },
  {
    label: "Underpromotion",
    value: "underpromotion",
    category: "specialMoves",
  },
  { label: "Equality", value: "equality", category: "goal" },
  { label: "Crushing", value: "crushing", category: "goal" },
  { label: "Advantage", value: "advantage", category: "goal" },
  { label: "Short puzzle", value: "shortPuzzle", category: "length" },
  { label: "One-move puzzle", value: "oneMovePuzzle", category: "length" },
  { label: "Long puzzle", value: "longPuzzle", category: "length" },
  { label: "Very long puzzle", value: "veryLongPuzzle", category: "length" },
];

export default themes;
