function user_schema(fname, lname, username, email, uid) {
  return {
    fname: fname,
    lname: lname,
    username: username,
    email: email,
    bullet: 1000,
    blitz: 1000,
    rapid: 1000,
    classical: 1000,
    correspondence: 1000,
    trainer: 1000,
    games_won: 0,
    games_lost: 0,
    games_drawn: 0,
    games_forfeited: 0,
    bullet_games_won: 0,
    bullet_games_lost: 0,
    bullet_games_drawn: 0,
    blitz_games_won: 0,
    blitz_games_lost: 0,
    blitz_games_drawn: 0,
    rapid_games_won: 0,
    rapid_games_lost: 0,
    rapid_games_drawn: 0,
    classical_games_won: 0,
    classical_games_lost: 0,
    classical_games_drawn: 0,
    correspondence_games_won: 0,
    correspondence_games_lost: 0,
    correspondence_games_drawn: 0,
    uid: uid,
    inbox: [],
    friends: [],
  };
}

export default user_schema;
